# Generated by Django 3.0 on 2020-01-07 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateField()),
                ('estilo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaNacimiento', models.DateField()),
                ('instrumentoPrincipal', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('coordenadaX', models.FloatField()),
                ('coordenadaY', models.FloatField()),
                ('grupo', models.ManyToManyField(to='Discografica.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('distribuidora', models.CharField(max_length=200)),
                ('fechaLanzamiento', models.DateField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discografica.Grupo')),
            ],
        ),
    ]
