
version: '3.7'

services:
   web:
      build: web
      ports:
         - 5000:5000
      command: 


         python manage.py runserver 0.0.0.0:5000
      
      volumes:
         - ./web:/web



# para la BD usamos sqlite, por defecto en django
