# docker-compose.yml
version: '3.7'

services:  # No repetir esta línea. Añadir debajo de los servicios existentes
   flask:
        build: 
          context: .
          dockerfile: flask_dockerfile
        ports:
          - "8080:5000"
        volumes:
          - ./flask:/flask
        working_dir: /flask